/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"

// Variáveis de controle de tempo e estado
volatile uint32_t tick_ms = 0;
volatile uint8_t presenca_detectada = 0;
volatile uint8_t alarme_ativo = 0;
volatile uint8_t carencia_ativa = 0;         // Nova flag: indica se o sistema está em "cooldown"
volatile uint32_t tempo_inicio_deteccao = 0;
volatile uint32_t tempo_inicio_carencia = 0; // Novo contador: marca quando a pessoa parou de se mover

void SysTick_Handler(void){
    tick_ms++;
}

void GPIO_Init(void) {
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_AFIOEN;

    GPIOA->CRL &= ~(0xFFFF0000);
    GPIOA->CRL |=  (0x33330000); // TODO: A4 CONFIGURADO COMO SAÍDA

    GPIOB->CRH &= ~(0x000000F0);
    GPIOB->CRH |=  (0x00000080);
    GPIOB->ODR &= ~(1 << 9);
}

void EXTI_Init(void) {
    AFIO->EXTICR[2] &= ~(0xF << 4);
    AFIO->EXTICR[2] |=  (0x1 << 4);

    EXTI->IMR |= (1 << 9);
    EXTI->RTSR |= (1 << 9);
    EXTI->FTSR |= (1 << 9);

    NVIC_EnableIRQ(EXTI9_5_IRQn);
    NVIC_SetPriority(EXTI9_5_IRQn, 1);
}

void TIM2_Init(void) {
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
    TIM2->PSC = 8000 - 1;
    TIM2->ARR = 250 - 1;
    TIM2->DIER |= TIM_DIER_UIE;
    TIM2->CR1 |= TIM_CR1_CEN;

    NVIC_EnableIRQ(TIM2_IRQn);
    NVIC_SetPriority(TIM2_IRQn, 2);
}

int main(void) {
    SysTick_Config(8000000 / 1000);

    GPIO_Init();
    GPIOA->BRR = (1 << 5) | (1 << 6) | (1 << 7);

    // Calibração reduzida para 3s durante os testes
    while(tick_ms < 60000) {
        if ((tick_ms % 1000) < 500) {
            GPIOA->BSRR = (1 << 5);
        } else {
            GPIOA->BRR = (1 << 5);
        }
    }

    GPIOA->BSRR = (1 << 5);

    EXTI_Init();
    TIM2_Init();

    while(1) {
        // ==============================================================
        // 1. ARMAR O ALARME (Filtro inicial de 2 segundos contínuos)
        // ==============================================================
        if (presenca_detectada && !alarme_ativo) {
            if ((tick_ms - tempo_inicio_deteccao) >= 5000) {
                alarme_ativo = 1;
                GPIOA->BSRR = (1 << 6);   // Liga LED Verde
                GPIOA->BSRR = (1 << 4); // GPIO QUE MANDA O SINAL DA NOTIFICAÇÃO PARA ESP32
            }
        }

        // ==============================================================
        // 2. DESARMAR O ALARME (Tempo de carência de 5 segundos)
        // ==============================================================
        if (carencia_ativa && alarme_ativo) {
            if ((tick_ms - tempo_inicio_carencia) >= 5000) { // 5000ms = 5s
                alarme_ativo = 0;         // Desarma tudo
                carencia_ativa = 0;
                GPIOA->BRR = (1 << 6);    // Desliga LED Verde
                GPIOA->BRR = (1 << 7);    // Silencia o Buzzer
            }
        }

        // __asm("nop");
    }
}

// Interrupção do Sensor
void EXTI9_5_IRQHandler(void) {
    if (EXTI->PR & (1 << 9)) {

        if (GPIOB->IDR & (1 << 9)) {
            // PESSOA SE MOVEU (Borda de subida)
            if (!presenca_detectada) {
                presenca_detectada = 1;
                carencia_ativa = 0; // Cancela a contagem de carência imediatamente

                if (!alarme_ativo) {
                    tempo_inicio_deteccao = tick_ms;
                }
            }
        } else {
            // PESSOA PAROU DE SE MOVER (Borda de descida)
            presenca_detectada = 0;

            if (alarme_ativo) {
                // Em vez de desligar, inicia o cronômetro de 5 segundos de carência
                carencia_ativa = 1;
                tempo_inicio_carencia = tick_ms;
            }
        }

        EXTI->PR = (1 << 9);
    }
}

// Interrupção do Timer (Cadência do Buzzer)
void TIM2_IRQHandler(void) {
    if (TIM2->SR & TIM_SR_UIF) {

        // O buzzer continua tocando se o alarme estiver ativo (mesmo durante os 5s de carência)
        if (alarme_ativo) {
            GPIOA->ODR ^= (1 << 7);
        } else {
            GPIOA->BRR = (1 << 7);
        }

        TIM2->SR &= ~TIM_SR_UIF;
    }
}
